version: "3"
services:
  pa-postgres:
    build:
      context: "."
      dockerfile: "./pgsql/Dockerfile"
    env_file:
      - "pgsql/postgres.env"
    ports:
      - "5432:5432"

  pa-server:
    build: "./api"
    ports:
     - "8080:8080"

  pa-client:
    build: ./client
    ports:
     - "3000:3000"
    depends_on:
      - pa-server

